#!/bin/sh
# This script updates your hosts file to its latest release along
# with your own custom hosts file, saved and controlled locally.
#
# Recommended hosts file here: https://github.com/StevenBlack/hosts

hosts_url="http://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
custom_hosts="${XDG_DATA_HOME:-$HOME/.config}/hosts"
system_hosts="/etc/hosts"

# Update system hosts file
sudo wget -qO "$system_hosts" "$hosts_url" && sudo chmod 644 "$system_hosts"

# Add custom hosts file to system hosts file
[ -f "$custom_hosts" ] && sudo tee -a "$system_hosts" <"$custom_hosts" >/dev/null
